#!/usr/bin/env python3
"""Generate UnimplementedOpcodes.hpp from docs/OPCODE_STATUS.md.

Extracts every opcode ID listed under a '**未实现**' table and emits a
header defining kUnimplementedOpcodes as an initializer list of uint16_t.

Re-run whenever opcodes are implemented or OPCODE_STATUS.md is regenerated.
"""
import re

STATUS = "/Users/xc5/dev/openrw/docs/OPCODE_STATUS.md"
OUT = "/Users/xc5/dev/openrw/rwengine/src/script/UnimplementedOpcodes.hpp"

with open(STATUS, encoding="utf-8") as f:
    text = f.read()

# Walk lines; when we hit '**未实现**' we are in an unimplemented table;
# a '### ' domain heading ends it.
unimpl = []
in_unimpl = False
for line in text.splitlines():
    if line.startswith("### "):
        in_unimpl = False
        continue
    if line.strip() == "**未实现**":
        in_unimpl = True
        continue
    if not in_unimpl:
        continue
    m = re.match(r'\|\s*0x([0-9a-f]{4})\s*\|', line)
    if m:
        unimpl.append(int(m.group(1), 16))

# de-dup, sort
unimpl = sorted(set(unimpl))
impl_count = 904 - len(unimpl)

with open(OUT, "w") as f:
    f.write("// AUTO-GENERATED by tools/gen_unimplemented_opcodes.py from\n")
    f.write("// docs/OPCODE_STATUS.md. Do not edit by hand; re-run the\n")
    f.write("// generator after implementing opcodes or regenerating the doc.\n")
    f.write("#pragma once\n\n")
    f.write("#include <cstdint>\n")
    f.write("#include <unordered_set>\n\n")
    f.write("namespace script {\n\n")
    f.write(f"// {len(unimpl)} unimplemented opcodes out of 904 "
            f"({impl_count} implemented).\n")
    f.write("inline const std::unordered_set<uint16_t>& unimplementedOpcodes() {\n")
    f.write("    static const std::unordered_set<uint16_t> set = {\n")
    for i in range(0, len(unimpl), 8):
        chunk = unimpl[i:i+8]
        f.write("        " + ", ".join(f"0x{o:04x}" for o in chunk) + ",\n")
    f.write("    };\n")
    f.write("    return set;\n")
    f.write("}\n\n")
    f.write("}  // namespace script\n")

print(f"wrote {OUT}: {len(unimpl)} unimplemented opcodes "
      f"({impl_count} implemented)")
